### ISSUE TITLE
Provide Container Digest without having to pull image

### ISSUE THREAD

**Issue by clbx** [microsoft/containerregistry#66]
As part of our processes we need to have some kind of verification that matches a downloaded container with one that exists remotely, the digest fills this, however I can't find any way to view the digest on docker hub, or otherwise remotely. 

Many other images have their digests available on the docker hub page such as [alpine](https://hub.docker.com/_/alpine?tab=tags&page=1&ordering=last_updated) However none of the Microsoft ones do. I'm specifically looking at the [dotnet sdk for nanoserver 1809](https://hub.docker.com/_/microsoft-dotnet-sdk/)

Is there a way to view digests before the image is downloaded, and if not can one be made available.

**Comment by rcowsill** [comment]
I think DockerHub doesn't show the digests for Microsoft images because they're hosted externally on Microsoft Container Registry. The equivalent digests for microsoft images are available through MCR's registry endpoint.

One way is to make a HEAD request and look at the `Docker-Content-Digest` response header:
```console
$ curl --head -H "Accept: application/vnd.docker.distribution.manifest.v2+json" https://mcr.microsoft.com/v2/dotnet/sdk/manifests/5.0.301-nanoserver-1809
HTTP/1.1 200 OK
[...]
Docker-Content-Digest: sha256:21ad8e949e5458ab47918a9c332aec7cd165ebaf8d0f1d981ef18b6b2e2f36d7
[...]
```

Alternatively, fetch the whole manifest and calculate its SHA256 hash:
```console
$ curl --silent -H "Accept: application/vnd.docker.distribution.manifest.v2+json" https://mcr.microsoft.com/v2/dotnet/sdk/manifests/5.0.301-nanoserver-1809 | sha256sum
21ad8e949e5458ab47918a9c332aec7cd165ebaf8d0f1d981ef18b6b2e2f36d7  -
```

To demonstrate that these both give the correct result you can fetch the manifest by hash:
```console
$ curl --silent -H "Accept: application/vnd.docker.distribution.manifest.v2+json" https://mcr.microsoft.com/v2/dotnet/sdk/manifests/sha256:21ad8e949e5458ab47918a9c332aec7cd165ebaf8d0f1d981ef18b6b2e2f36d7 | sha256sum
21ad8e949e5458ab47918a9c332aec7cd165ebaf8d0f1d981ef18b6b2e2f36d7  -
```

Specifying the `Accept: [...]` header is important in all of these examples, without it you'll get the V1 manifest and the digest will be different.

Also, if you're using the digests shown on Docker Hub (where available), these issue threads are worth reading: 
docker/hub-feedback#1925
moby/moby#40636

**Comment by clbx** [comment]
This is wildly helpful, thank you @rcowsill
