### ISSUE TITLE
Docker tag runtime-deps:3.1.18-alpine3.13 Does Not Exist

### ISSUE THREAD

**Issue by craig-plutoflume** [microsoft/containerregistry#76]
According to [here](https://mcrflowprodcentralus.data.mcr.microsoft.com/mcrprod/dotnet/runtime-deps?P1=1628768178&P2=1&P3=1&P4=UU3EOcZIUZRUNa3%2FnGcGzrHon5ZsS%2BM%2BW7UGmjAmDQk%3D&se=2021-08-12T11%3A36%3A18Z&sig=ME4rhC3BhPRRFUd4Oc7Mcp74u1VSkVhbwYR41cP8Els%3D&sp=r&sr=b&sv=2015-02-21) and [here](https://hub.docker.com/_/microsoft-dotnet-runtime-deps?tab=description) this docker image/tag should exist (it's been more than 12 hours since the release).  The tag for runtime-deps:3.1.18-bionic is there, so I think something was missed for the alpine 3.13 image.

**Comment by craig-plutoflume** [comment]
Just a bit more info:
```
$ docker pull mcr.microsoft.com/dotnet/core/runtime-deps:3.1.18-alpine3.13
Error response from daemon: manifest for mcr.microsoft.com/dotnet/core/runtime-deps:3.1.18-alpine3.13 not found: manifest unknown: manifest tagged by "3.1.18-alpine3.13" is not found
```
Vs 
```
$ docker pull mcr.microsoft.com/dotnet/core/runtime-deps:3.1.15-alpine3.12
3.1.15-alpine3.12: Pulling from dotnet/core/runtime-deps
339de151aab4: Pull complete
60f4ec0d2258: Pull complete
Digest: sha256:58bfdaff2acd6d8f6aacbd6bfd19b95c3bfa5fef9c0819603ef7c827839fe5c1
Status: Downloaded newer image for mcr.microsoft.com/dotnet/core/runtime-deps:3.1.15-alpine3.12
mcr.microsoft.com/dotnet/core/runtime-deps:3.1.15-alpine3.12
```

**Comment by mthalman** [comment]
The repository you're referencing is `mcr.microsoft.com/dotnet/core/runtime-deps`.  Instead, you should be using `mcr.microsoft.com/dotnet/runtime-deps`.  This is related to the [repo migration](https://github.com/dotnet/dotnet-docker/issues/2375) announced last year.   Since 3.1.18 is a new tag, it was only published to the `mcr.microsoft.com/dotnet/runtime-deps` repository and not `mcr.microsoft.com/dotnet/core/runtime-deps`.  Existing tags for supported versions that had previously been published in `mcr.microsoft.com/dotnet/core/runtime-deps` are still being maintained.

**Comment by craig-plutoflume** [comment]
Thanks @mthalman!
