### ISSUE TITLE
How to migrate from microsoft/dotnet:2.2-sdk ??

### ISSUE THREAD

**Issue by kyojunlee** [microsoft/containerregistry#85]
there is no mcr.microsoft.com/dotnet/sdk:2.2.
Any guide would be appricated.
Thanks.

**Comment by mthalman** [comment]
.NET Core 2.2 has been EOL since Dec 2019.  It was already EOL at the time the migration from the mcr.microsoft.com/dotnet/_core_/sdk repository to mcr.microsoft.com/dotnet/sdk and so 2.2 tags were not included in that migration.  You can still access 2.2 tags at the original mcr.microsoft.com/dotnet/core/sdk repository (e.g. `mcr.microsoft.com/dotnet/core/sdk:2.2`).  However, it is recommended to upgrade to a supported version of .NET Core.

**Comment by bariscaglar** [comment]
Closing the issue as it appears the question has been answered. Please reopen if further information is needed.
